### ISSUE TITLE
Unable to configure connection timeout for JunOS driver

### ISSUE THREAD

**Issue by alcm-b** [napalm-automation/napalm#1115] opened 2020-01-31 17:36 UTC
### Description of Issue/Question

When NAPALM connects to a JunOS device that is down, `Driver.open()` falls back
to a default connection timeout, which is 30 seconds or so. In some cases there
is a need to reduce or increase that timeout.

For example, if NAPALM is used to query many devices, such as from a long
Nornir inventory, when some of the devices are not available, a long connection
timeout slows down the whole process.

I tried a parameter `NetworkDriver(..., timeout)`
(https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver
), found that it works for IOS driver, but not for JunOS.

`jnpr` authors have a solution, described in an issue https://github.com/Juniper/py-junos-eznc/issues/780 from `jnpr` module perspective. @stacywsmith
suggested to use `auto_probe`:

```
>>> dev = Device(host='r0', user='user', passwd='user123', port=666)
>>> dev.open(auto_probe=5)
```

On NAPALM side, timeout for JunOS is set only after the connection is already
open, so it does not affect connection timeout:
https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L126

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
```

### Network operating system version

```
not applicable
```

### Steps to Reproduce the Issue

- install NAPALM
- pick a host that is down (ssh connection to which would fail with 'Connection
  timed out')
- Using NAPALM, create a NetworkDriver object with JunOS driver and a custom
  timeout that is either shorter or longer than the default one, for example:
  `NetworkDriver(..., timeout=5)`
- open a connection to that host with `open()`

**Expected**

`NetworkDriver().open()` fails with an exception after a number of seconds
specified in `timeout` parameter.

**Actual**

`NetworkDriver().open()` fails with an exception after 30 seconds, no matter
what is the value of `timeout`.

### Error Traceback

Reproducer:

```python
import traceback; from datetime import datetime; import sys; import napalm
unavailable_host, timeout = '192.0.2.123', 5 # seconds
summary = [napalm.__version__, sys.version]
for drivername in ['ios', 'junos']:
    now = datetime.now()
    driver = napalm.get_network_driver(drivername)
    try:
        driver(hostname=unavailable_host, username='user', password='1', timeout=timeout).open()
    except Exception as e:
        msg = "{} timed out after {} seconds with {}"
        summary.insert(2, msg.format(drivername, (datetime.now() - now).seconds, str(e.__class__.__name__)))
        summary.append(traceback.format_exc())
print('\n---\n'.join(summary))
```

Traceback:

```
In [73]: import traceback; from datetime import datetime; import sys; import napalm
    ...: unavailable_host, timeout = '192.0.2.123', 5 # seconds
    ...: summary = [napalm.__version__, sys.version]
    ...: for drivername in ['ios', 'junos']:
    ...:     now = datetime.now()
    ...:     driver = napalm.get_network_driver(drivername)
    ...:     try:
    ...:         driver(hostname=unavailable_host, username='user', password='1', timeout=timeout).open()
    ...:     except Exception as e:
    ...:         msg = "{} timed out after {} seconds with {}"
    ...:         summary.insert(2, msg.format(drivername, (datetime.now() - now).seconds, str(e.__class__.__name__)))
    ...:         summary.append(traceback.format_exc())
    ...: print('\n---\n'.join(summary))
    ...:
    ...:
2.5.0
---
3.7.3 (default, Oct  7 2019, 12:56:13)
[GCC 8.3.0]
---
junos timed out after 31 seconds with ConnectionException
---
ios timed out after 5 seconds with ConnectionException
---
Traceback (most recent call last):
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/netmiko/base_connection.py", line 884, in         establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/paramiko/util.py", line 283, in retry_on_signal
    return function()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/napalm/base/base.py", line 96, in _netmiko_open
    **netmiko_optional_args
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 246, in          ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/netmiko/base_connection.py", line 890, in         establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 192.0.2.123:22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-73-1a49c1a876cc>", line 8, in <module>
    driver(hostname=unavailable_host, username='user', password='1', timeout=timeout).open()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/napalm/ios/ios.py", line 169, in open
    device_type, netmiko_optional_args=self.netmiko_optional_args
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/napalm/base/base.py", line 99, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 192.0.2.123

---
Traceback (most recent call last):
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/jnpr/junos/device.py", line 1264, in open
    self.__class__.ON_JUNOS})
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/ncclient/manager.py", line 176, in connect
    return connect_ssh(*args, **kwds)
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/ncclient/manager.py", line 141, in connect_ssh
    session.connect(*args, **kwds)
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 291, in connect
    raise SSHError("Could not open socket to %s:%s" % (host, port))
ncclient.transport.errors.SSHError: Could not open socket to 192.0.2.123:22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/napalm/junos/junos.py", line 126, in open
    self.device.open()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/jnpr/junos/device.py", line 1287, in open
    raise EzErrors.ConnectTimeoutError(self)
jnpr.junos.exception.ConnectTimeoutError: ConnectTimeoutError(192.0.2.123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-73-1a49c1a876cc>", line 8, in <module>
    driver(hostname=unavailable_host, username='user', password='1', timeout=timeout).open()
  File "/home/user1/.local/share/virtualenvs/xxx-f88TS9VW/lib/python3.7/site-packages/napalm/junos/junos.py", line 128, in open
    raise ConnectionException(cte.msg)
napalm.base.exceptions.ConnectionException: None

```

**Comment by ktbyers** [comment] 2020-02-01 17:27
@alcm-b 

Reading more per the issue you referenced on PyEZ

https://github.com/Juniper/py-junos-eznc/issues/780

It sounds like the issue is more Juniper's timeout doesn't actually have a direct connection timeout. In other words, the PyEZ timeout is an RPC timeout post connection and not an authentication timeout.

Probably the best course would be add an "optional_args" into NAPALM to support auto_probe. This would allow an end-user to pass auto_probe in using something like:

```
optional_args = {
    "auto_probe": 5
}
```
This is in addition to the normal arguments you pass into NAPALM.

I don't think we should wire auto_probe into NAPALM's timeout as that would be a confusing way of overloading NAPALM's timeout.

Do you want to make a PR on this?

**Comment by alcm-b** [comment] 2020-02-04 08:46
@ktbyers , yes, I'll work on a fix for that.

**Comment by alcm-b** [comment] 2020-02-04 11:36
@ktbyers may I assume there is no Python 2 compatibility required?

https://github.com/napalm-automation/napalm/releases

> 2.5.0
> This is the last release supporting Python 2. Going forward, we will only support Python 3.6+

**Comment by ktbyers** [comment] 2020-02-04 17:08
Yes, develop branch for NAPALM has already removed PY2 support so going forward there is no PY2 compatibility.

**Comment by alcm-b** [comment] 2020-02-05 11:05
@ktbyers please take a look - https://github.com/napalm-automation/napalm/pull/1117

**Comment by alcm-b** [comment] 2020-02-05 11:16
I ran a test script with the new optional argument `auto_probe` :

```
In [4]: import traceback; from datetime import datetime; import sys; import napalm
   ...: unavailable_host, timeout = '192.0.2.123', 5 # seconds
   ...: summary = [napalm.__version__, sys.version]
   ...: optional_args = dict(auto_probe=5)
   ...: for drivername in ['ios', 'junos']:
   ...:     now = datetime.now()
   ...:     driver = napalm.get_network_driver(drivername)
   ...:     try:
   ...:         driver(hostname=unavailable_host, username='user', password='1', timeout=timeout, optional_args=optional_args).open()
   ...:     except Exception as e:
   ...:         msg = "{} timed out after {} seconds with {}"
   ...:         summary.insert(2, msg.format(drivername, (datetime.now() - now).seconds, str(e.__class__.__name__)))
   ...:         summary.append(traceback.format_exc())
   ...: print('\n---\n'.join(summary))
3.0.0
---
3.7.3 (default, Oct  7 2019, 12:56:13)
[GCC 8.3.0]
---
junos timed out after 6 seconds with ConnectionException
---
ios timed out after 5 seconds with ConnectionException
---
Traceback (most recent call last):
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/netmiko-3.0.0-py3.7.egg/netmiko/base_connection.py", line 892, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/paramiko-2.7.1-py3.7.egg/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/paramiko-2.7.1-py3.7.egg/paramiko/util.py", line 283, in retry_on_signal
    return function()
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/paramiko-2.7.1-py3.7.egg/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ref/github.com/alcm-b/napalm/napalm/base/base.py", line 92, in _netmiko_open
    **netmiko_optional_args
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/netmiko-3.0.0-py3.7.egg/netmiko/ssh_dispatcher.py", line 252, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/netmiko-3.0.0-py3.7.egg/netmiko/base_connection.py", line 318, in __init__
    self._open()
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/netmiko-3.0.0-py3.7.egg/netmiko/base_connection.py", line 323, in _open
    self.establish_connection()
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/netmiko-3.0.0-py3.7.egg/netmiko/base_connection.py", line 898, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: cisco_ios 192.0.2.123:22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-4-324287c30d53>", line 9, in <module>
    driver(hostname=unavailable_host, username='user', password='1', timeout=timeout, optional_args=optional_args).open()
  File "/srv/ref/github.com/alcm-b/napalm/napalm/ios/ios.py", line 164, in open
    device_type, netmiko_optional_args=self.netmiko_optional_args
  File "/srv/ref/github.com/alcm-b/napalm/napalm/base/base.py", line 95, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 192.0.2.123

---
Traceback (most recent call last):
  File "/srv/ref/github.com/alcm-b/napalm/napalm/junos/junos.py", line 125, in open
    self.device.open(auto_probe=self.auto_probe)
  File "/home/alf/.virtualenvs/napalm-test/lib/python3.7/site-packages/junos_eznc-2.3.1-py3.7.egg/jnpr/junos/device.py", line 1277, in open
    raise EzErrors.ProbeError(self)
jnpr.junos.exception.ProbeError: ProbeError(192.0.2.123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ipython-input-4-324287c30d53>", line 9, in <module>
    driver(hostname=unavailable_host, username='user', password='1', timeout=timeout, optional_args=optional_args).open()
  File "/srv/ref/github.com/alcm-b/napalm/napalm/junos/junos.py", line 127, in open
    raise ConnectionException(cte.msg) from cte
napalm.base.exceptions.ConnectionException: None
```

**Comment by alcm-b** [comment] 2020-02-05 11:20
Without the `auto_probe` option, default timeout is in effect:

```
In [5]: import traceback; from datetime import datetime; import sys; import napalm
   ...: unavailable_host, timeout = '192.0.2.123', 5 # seconds
   ...: summary = [napalm.__version__, sys.version]
   ...: for drivername in ['ios', 'junos']:
   ...:     now = datetime.now()
   ...:     driver = napalm.get_network_driver(drivername)
   ...:     try:
   ...:         driver(hostname=unavailable_host, username='user', password='1', timeout=timeout).open()
   ...:     except Exception as e:
   ...:         msg = "{} timed out after {} seconds with {}"
   ...:         summary.insert(2, msg.format(drivername, (datetime.now() - now).seconds, str(e.__class__.__name__)))
   ...:         # XXX summary.append(traceback.format_exc())
   ...: print('\n---\n'.join(summary))
3.0.0
---
3.7.3 (default, Oct  7 2019, 12:56:13)
[GCC 8.3.0]
---
junos timed out after 31 seconds with ConnectionException
---
ios timed out after 5 seconds with ConnectionException
```

**Comment by ktbyers** [comment] 2020-02-12 17:43
PR with this fix was merged.

**Closed by ktbyers** 2020-02-12 17:43 UTC
