### ISSUE TITLE
when using nxos_ssh when changing hostname receive error

### ISSUE THREAD

**Issue by omershtivi** [napalm-automation/napalm#637] opened 2018-01-29 17:01 UTC
When used nxos_ssh changing device hostname I received the following issue:
`fatal: [LAB_POD2_1]: FAILED! => {"changed": false, "failed": true, "msg": "cannot install config: Search pattern never detected in send_command_expect: LAB\\_POD2\\_1\\-TEST\\#"}`

Rerun the playbook Password OK

The playbook:
```
omers@Ubuntu-Ansible-CTL:~/Naplam-Tests$ more Playbooks/Basic-Config-Checkpoint-Dryrun.yml
---
- name: Configuration replace
  hosts: N9K
  connection: local
  gather-facts: False
  tasks:
      - name: Generate-Configuration N9K
        template: src=../Templates/N9K-Checkpoint.j2 dest=../Configuration/{{ inventory_hostname }}

      - name: N9K Configuration Replace Check
        napalm_install_config:
             hostname: "{{ ip_address }}"
             username: "{{ username }}"
             password: "{{ password }}"
             dev_os: "{{ dev_os }}"
             config_file: ../Configuration/{{ inventory_hostname }}
             commit_changes: False
             replace_config: True
             diff_file: ../Diff/initial.diff
```

**Comment by lazhao123** [comment] 2019-06-05 23:20
I got same issue on Linux when I config cisco nxos. I am using NAPALM version 2.4.0.
The script call commit_config() to change hostname.
The bug is caused by self.base_prompt, since hostname is changed, while base_prompt is not changed yet. That caused pattern not match, and timeout. Is anyone working on this?

    def _read_channel_expect(self, pattern="", re_flags=0, max_loops=150):
        output = ""
        if not pattern:
            pattern = re.escape(self.base_prompt)           <=== base_prompt not match with hostname.
        log.debug("Pattern is: {}".format(pattern))

traceback
=========================
  File "/root/learn_lab/net-auto/switch_dev.py", line 86, in <module>
    nxos_dev.set_hostname('N3k-1')
  File "/root/learn_lab/net-auto/switch_dev.py", line 52, in set_hostname
    self._driver.commit_config()
  File "/root/global3_venv/lib64/python3.6/site-packages/napalm/nxos/nxos.py", line 224, in commit_config
    self._copy_run_start()
  File "/root/global3_venv/lib64/python3.6/site-packages/napalm/nxos_ssh/nxos_ssh.py", line 496, in _copy_run_start
    output = self.device.save_config()
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 214, in save_config
    self.enable()
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 22, in enable
    cmd=cmd, pattern=pattern, re_flags=re_flags
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1406, in enable
    if not self.check_enable_mode():
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 16, in check_enable_mode
    check_string=check_string
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1386, in check_enable_mode
    output = self.read_until_prompt()
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 590, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/root/global3_venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment] 2019-06-05 23:34
Okay, let me test...adding @carlniger onto this issue also.

**Comment by lazhao123** [comment] 2019-06-05 23:46
Great!

**Comment by carlniger** [comment] 2019-06-06 22:27
Tested and confirmed I can reproduce this. Spoke w/ @ktbyers and I have a really hack-y fix in place based on his input. Will try to clean it up and open a PR in the next day or so!

**Comment by lazhao123** [comment] 2019-06-10 03:54
Good job! Carlniger.
How do I get the fix? Will it be released soon?

**Comment by carlniger** [comment] 2019-06-10 13:50
@lazhao123 you can clone my commit in the pr at #990 or wait till that gets hopefully approved/merged!

**Comment by lazhao123** [comment] 2019-06-16 00:42
Tested, good work!

**Comment by ktbyers** [comment] 2019-06-16 03:13
I get an exception in a different place if I try to change the hostname using nxos_ssh:

```
../../../napalm_auto_test/napalm/napalm/nxos/nxos.py:220: in commit_config
    self._load_cfg_from_checkpoint()
../../../napalm_auto_test/napalm/napalm/nxos_ssh/nxos_ssh.py:532: in _load_cfg_from_checkpoint
    rollback_result = self._send_command_list(commands)
../../../napalm_auto_test/napalm/napalm/nxos_ssh/nxos_ssh.py:457: in _send_command_list
    command, strip_prompt=False, strip_command=False
```

**Comment by ktbyers** [comment] 2019-06-16 18:29
I think we need two fixes here, both Carl's and also something for the hostname change itself:

```diff
diff --git a/napalm/nxos_ssh/nxos_ssh.py b/napalm/nxos_ssh/nxos_ssh.py
index a43f0310..55536c49 100644
--- a/napalm/nxos_ssh/nxos_ssh.py
+++ b/napalm/nxos_ssh/nxos_ssh.py
@@ -449,12 +449,15 @@ class NXOSSSHDriver(NXOSDriverBase):
         """
         return self.device.send_command(command)
 
-    def _send_command_list(self, commands):
+    def _send_command_list(self, commands, expect_string=None):
         """Wrapper for Netmiko's send_command method (for list of commands."""
         output = ""
         for command in commands:
             output += self.device.send_command(
-                command, strip_prompt=False, strip_command=False
+                command,
+                strip_prompt=False,
+                strip_command=False,
+                expect_string=expect_string,
             )
         return output
 
@@ -528,10 +531,13 @@ class NXOSSSHDriver(NXOSDriverBase):
             "rollback running-config file {}".format(self.candidate_cfg),
             "no terminal dont-ask",
         ]
+
         try:
-            rollback_result = self._send_command_list(commands)
+            rollback_result = self._send_command_list(commands, expect_string=r"#")
         finally:
             self.changed = True
+        # If hostname changes ensure Netmiko state is updated properly
+        self.device.set_base_prompt()
         msg = rollback_result
         if "Rollback failed." in msg:
             raise ReplaceConfigException(msg)
```

**Comment by ktbyers** [comment] 2019-06-18 19:12
Should be fixed by https://github.com/napalm-automation/napalm/pull/999

**Closed by ktbyers** 2019-06-18 19:12 UTC
Labels: Info needed, bug, nxos-ssh

**Comment by lazhao123** [comment] 2019-06-24 22:44
Hello Kirk,

Can you please check my comments?
https://github.com/napalm-automation/napalm/pull/999
