### ISSUE TITLE
Cisco device error in the log

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#728] opened 2018-05-16 13:07 UTC
I see this error continuously logged in my proxy minion for cisco device:
Exception argument of type 'bool' is not iterable occurred in scheduled job

Any idea about this error?

**Comment by mirceaulinic** [comment] 2018-05-21 14:04
This is a duplicate of https://github.com/napalm-automation/napalm-salt/issues/49 and https://github.com/saltstack/salt/issues/47695.

**Closed by mirceaulinic** 2018-05-21 14:04 UTC
Labels: duplicate
