### ISSUE TITLE
ValueError: requested attribute name cu already exists

### ISSUE THREAD

**Issue by vnitinv** [napalm-automation/napalm#127] opened 2016-01-04 09:05 UTC
If we call open() function twice(junos devices), it throws exception which doesn't give proper message atleast. Should be handled in better way
>>> obj = driver('xxxx', 'xxx', 'xxxxx')
>>> obj.open()
>>> 
>>> obj.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nitinkr/Coding/PyEZ_env/napalm_env/env/lib/python2.7/site-packages/napalm/junos.py", line 43, in open
    self.device.bind(cu=Config)
  File "/Users/nitinkr/Coding/PyEZ_env/napalm_env/env/lib/python2.7/site-packages/jnpr/junos/device.py", line 756, in bind
    name)
ValueError: requested attribute name cu already exists

**Comment by ncostaa** [comment] 2016-01-19 17:41
I'm getting this error with my junos file when i try to load some xml. But, when i use the xml directly in the script it works perfectly. What did you do to handle this?

**Comment by dbarrosop** [comment] 2016-01-22 08:43
@ncostaa can you send the traceback and the code that is triggering your issue? Usually pyez raises that Exception with that message when you open the connection multiple times.

**Comment by ncostaa** [comment] 2016-01-22 23:46
Hi @dbarrosop here is the log file gave by the worker from celery:

---------------------------------------------------------------------------------------------------------------------------------------
[2016-01-20 01:20:48,639: INFO/MainProcess] Received task: tasks.router_fod[edb8d5e3-fd55-4827-8622-a6180f31d30e]
[2016-01-20 01:20:48,681: INFO/Worker-1] Connected (version 2.0, client OpenSSH_5.9)
[2016-01-20 01:20:48,906: INFO/Worker-1] Auth banner: Hello, user!

[2016-01-20 01:20:48,907: INFO/Worker-1] Authentication (password) successful!
[2016-01-20 01:20:49,531: INFO/Worker-1] initialized: session-id=2819 | server_capabilities=['http://xml.juniper.net/dmi/system/1.0', 'urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0', 'http://xml.juniper.net/netconf/junos/1.0', 'urn:ietf:params:xml:ns:netconf:capability:validate:1.0', 'urn:ietf:params:xml:ns:netconf:capability:candidate:1.0', 'urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file', 'urn:ietf:params:xml:ns:netconf:base:1.0']
[2016-01-20 01:20:49,532: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:49,650: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:49,769: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:49,835: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:49,964: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:50,090: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:50,207: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:50,354: INFO/Worker-1] Connected (version 2.0, client OpenSSH_5.9)
[2016-01-20 01:20:50,629: INFO/Worker-1] Auth banner: Hello, user!

[2016-01-20 01:20:50,630: INFO/Worker-1] Authentication (password) successful!
[2016-01-20 01:20:51,203: INFO/Worker-1] initialized: session-id=2824 | server_capabilities=['http://xml.juniper.net/dmi/system/1.0', 'urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0', 'http://xml.juniper.net/netconf/junos/1.0', 'urn:ietf:params:xml:ns:netconf:capability:validate:1.0', 'urn:ietf:params:xml:ns:netconf:capability:candidate:1.0', 'urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file', 'urn:ietf:params:xml:ns:netconf:base:1.0']
[2016-01-20 01:20:51,204: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,322: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,439: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,563: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,631: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,750: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,869: INFO/Worker-1] Requesting 'ExecuteRpc'
[2016-01-20 01:20:51,986: WARNING/Worker-1] Device(192.168.10.1)
[2016-01-20 01:20:52,053: ERROR/MainProcess] Task tasks.router_fod[edb8d5e3-fd55-4827-8622-a6180f31d30e] raised unexpected: ValueError('requested attribute name cu already exists',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/nuno/Documents/project/tasks.py", line 31, in router_fod

**Comment by dbarrosop** [comment] 2016-01-24 19:39
That error is usually triggered when try to open the same device twice. From the logs from celery is hard to say. Could you provide some code that we can use to reproduce the issue from a python shell?

**Comment by ncostaa** [comment] 2016-01-24 21:46
Hi David, tks for your response. The problem was exactly that,  multiple
connections to the device. I was using celery to perform the tasks and he
was simultaneasly binding dev to cu creating the error. The problem was the
lack of information about this issue.. and it should be handle better.

Regards,
Nuno Costa

**Comment by dbarrosop** [comment] 2016-01-25 08:01
Glad to hear you found the issue. We have plans to handle errors in a better way but right now we are focusing on creating something that brings value to as many folks as possible hoping to get more contributors. Sorry for the inconvenience.

**Comment by jathanism** [comment] 2016-01-29 03:49
I'm currently testing out NAPALM and running into the same issue. If someone doesn't beat me to it, I'll happily provide a patch soon.

**Comment by dbarrosop** [comment] 2016-01-29 20:48
That would be really cool, we definitively should start working on improving stability and error handling. As a first step the next version will support the python context manager, so you will be able to do:

    driver = get_network_driver(my_vendor_os)
    with driver(ip, user, password) as device:
        facts = device.get_facts()
        device.load_candidate_replace(new_config)
        device.commit()

I guess you get the point : ) The main benefit is that you will not have to care about opening or closing the device (so no more opening) twice and that the manager will try to handle error better or ask you to fill a bug if the exception wasn't handled better. If you still want to use the open and the close methods you will also be able to keep doing it.

**Comment by dbarrosop** [comment] 2016-04-26 04:38
The context manager is already implemented and it's the preferred way of using the driver so this issue shouldn't happen anymore.

**Closed by dbarrosop** 2016-04-26 04:38 UTC
