### ISSUE TITLE
net.facts not working on nexus switch driver(nxos_ssh) in the upgraded version of (napalm 2.5.0).

### ISSUE THREAD

**Issue by saifk-20786** [napalm-automation/napalm#1082] opened 2019-11-06 07:19 UTC
### Description of Issue/Question
net.facts not working on nexus switch driver(nxos_ssh) in the upgraded version of (napalm 2.5.0).
However, net.facts works perfectly fine when i install napalm 2.4.0 as expected.
*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
~# salt-minion --version
salt-minion 2019.2.2 (Fluorine)
~# salt-master --version
salt-master 2019.2.2 (Fluorine)

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
napalm-base==1.0.0
napalm-ios==0.8.1
napalm-iosxr==0.5.6
napalm-junos==0.12.1
napalm-nxos==0.7.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
s Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2013, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

        Software
          BIOS:      version 3.5.0
          loader:    version N/A
          kickstart: version 6.0(2)N2(1)
          system:    version 6.0(2)N2(1)
          Power Sequencer Firmware:
                     Module 1: version v1.0
                     Module 3: version v2.0
          Microcontroller Firmware:        version v1.2.0.1
          SFP uC:    Module 1: v1.0.0.0
          QSFP uC:   Module not detected
          BIOS compile time:       02/03/2011
          kickstart image file is: bootflash:///n5000-uk9-kickstart.6.0.2.N2.1.bin
          kickstart compile time:  7/24/2013 3:00:00 [07/24/2013 10:49:21]
          system image file is:    bootflash:///n5000-uk9.6.0.2.N2.1.bin
          system compile time:     7/24/2013 3:00:00 [07/24/2013 12:42:28]


        Hardware
          cisco Nexus5548 Chassis ("O2 32X10GE/Modular Universal Platform Supervisor")
          Intel(R) Xeon(R) CPU         with 8253856 kB of memory.
          Processor Board ID FOC16130WSQ

          Device name: host
          bootflash:    2007040 kB

        Kernel uptime is 1230 day(s), 9 hour(s), 51 minute(s), 19 second(s)

        Last reset
          Reason: Unknown
          System version: 6.0(2)N2(1)
          Service:

        plugin
          Core Plugin, Ethernet Plugin
```

### Steps to Reproduce the Issue
How to Reproduce

1) Get package from 'pip install napalm --upgrade'
2) Then run 'salt "host" net.facts'
3) An error occurs.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 178, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm/nxos_ssh/nxos_ssh.py", line 588, in get_facts
            "show inventory | json", "TABLE_inv", "ROW_inv"
          File "/usr/local/lib/python2.7/dist-packages/napalm/nxos/nxos.py", line 639, in _get_command_table
            json_output = json.loads(json_output)
          File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
            return _default_decoder.decode(s)
          File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
            raise ValueError("No JSON object could be decoded")
        ValueError: No JSON object could be decoded
```

**Comment by mirceaulinic** [comment] 2019-11-06 14:12
Hey @saifk-20786 would you be able to provide the output from `show inventory | json` and `show inventory`?
Also, are you seeing any issues with the `nxos` driver (not nxos-ssh)?
FYI: you don't need the `napalm-*` packages - `napalm` is all you need.

**Comment by seismiccollision** [comment] 2019-11-06 23:30
i'm gonna guess it's because before nxos 7.x there is no support for "| json"
just ran into this on 6.x and 5.x nxos

**Comment by saifk-20786** [comment] 2019-11-07 03:48
# show inventory | json
                                  ^
% Invalid command at '^' marker.

==============================
# show inventory
NAME: "Chassis", DESCR: "Nexus5548 Chassis"
PID: N5K-C5548UP       , VID: V01 , SN: SSI155206VG

NAME: "Module 1", DESCR: "O2 32X10GE/Modular Universal Platform Supervisor"
PID: N5K-C5548UP       , VID: V01 , SN: FOC16130WSQ

NAME: "Fan 1", DESCR: "Chassis fan module"
PID: N5548P-FAN        , VID: N/A , SN: N/A

NAME: "Fan 2", DESCR: "Chassis fan module"
PID: N5548P-FAN        , VID: N/A , SN: N/A

NAME: "Power supply 1", DESCR: "AC power supply"
PID: N55-PAC-750W      , VID: V01 , SN: ART1552X1QW

NAME: "Power supply 2", DESCR: "AC power supply"
PID: N55-PAC-750W      , VID: V02 , SN: POG16147T6G

NAME: "Module 3", DESCR: "O2 Non L3 Daughter Card"
PID: N55-DL2           , VID: V01 , SN: FOC16156F2F

======================================
hi @mirceaulinic i tried with nxos driver too. but the proxies didn't start with the nxos driver, it throw an error.
```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4292b69780>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.20.249.2', port=443): Max retries exceeded with url: /ins (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4292b69780>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nxapi_plumbing/api_client.py", line 64, in _send_request
    verify=self.verify,
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.20.249.2', port=443): Max retries exceeded with url: /ins (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4292b69780>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/napalm/nxos/nxos.py", line 629, in open
    self._send_command("show hostname")
  File "/usr/local/lib/python3.5/dist-packages/napalm/nxos/nxos.py", line 643, in _send_command
    return self.device.show(command, raw_text=raw_text)
  File "/usr/local/lib/python3.5/dist-packages/nxapi_plumbing/device.py", line 61, in show
    result = self.show_list(commands, raw_text)
  File "/usr/local/lib/python3.5/dist-packages/nxapi_plumbing/device.py", line 89, in show_list
    return self.api._nxapi_command(commands, method=cmd_method)
  File "/usr/local/lib/python3.5/dist-packages/nxapi_plumbing/api_client.py", line 105, in _nxapi_command
    response = self._send_request(commands, method=method)
  File "/usr/local/lib/python3.5/dist-packages/nxapi_plumbing/api_client.py", line 67, in _send_request
    raise NXAPIConnectionError(str(e))
nxapi_plumbing.errors.NXAPIConnectionError: HTTPSConnectionPool(host='172.20.249.2', port=443): Max retries exceeded with url: /ins (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4292b69780>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/napalm.py", line 340, in get_device
    network_device.get('DRIVER').open()
  File "/usr/local/lib/python3.5/dist-packages/napalm/nxos/nxos.py", line 632, in open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 172.20.249.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 1027, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 1226, in connect_master
    yield self._post_master_init(master)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3.5/types.py", line 177, in send
    return self.__wrapped.send(val)
  File "/usr/local/lib/python3.5/dist-packages/salt/metaproxy/proxy.py", line 160, in post_master_init
    proxy_init_fn(self.opts)
  File "/usr/local/lib/python3.5/dist-packages/salt/proxy/napalm.py", line 206, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/napalm.py", line 354, in get_device
    raise napalm_base.exceptions.ConnectionException(base_err_msg)
napalm.base.exceptions.ConnectionException: Cannot connect to 172.20.249.2 as svcnetauto.
```

**Comment by ktbyers** [comment] 2019-11-07 04:32
I think an issue was probably introduced in this PR:

 https://github.com/napalm-automation/napalm/pull/1025

It looks like that PR probably switched it to require the `| json` which will then fail for a set of NX-OS platforms that don't have the `| json` capability.

**Comment by AmbicaY** [comment] 2019-11-07 07:27
I think its due to json capability. Most of my nxos fleet is not on nxos 7.x and I can repro this issue.

**Comment by mirceaulinic** [comment] 2019-11-11 08:45
CC @VictorPavlushin - would you like to take a look at this? Cheers.

**Comment by VictorPavlushin** [comment] 2019-11-11 09:47
I have no way to check other firmware versions. I have 6000 and 9000 devices. They have installed version 7 of the firmware. What is your version?

**Comment by VictorPavlushin** [comment] 2019-11-11 12:35
@saifk-20786 I will try to fix it soon.
Please advise on which 6.x versions it works and on which not.

**Comment by saifk-20786** [comment] 2019-11-11 12:50
@VictorPavlushin its not working on all 6.x versions, i mean its not woking for the devices which are below 7.x version.

**Comment by mirceaulinic** [comment] 2019-11-12 08:01
@saifk-20786 can you try the @VictorPavlushin's fix in #1084?

**Comment by seismiccollision** [comment] 2019-11-12 18:30
tested on 6.x and 5.x and seems to be working for me for what it's worth
(is there a right way to test the module? without knowing better i just replaced the nxos_ssh.py file in my install directory)
this is a nice addition to get the serial numbers right
thanks guys!

**Comment by saifk-20786** [comment] 2019-11-13 05:43
> @saifk-20786 can you try @VictorPavlushin's fix in #1084?

i tried @VictorPavlushin's fix in #1084 
seems to be working, but the output is not accurate. please take a look.
hostname and fqdn is not printed correct and the serial number is empty.
``` salt "host" net.facts
host:
    ----------
    comment:
    out:
        ----------
        fqdn:
            status

            --------------------------------------------------------------------------------
            Port          Name               Status    Vlan      Duplex  Speed   Type
            --------------------------------------------------------------------------------
            Eth1/1       **********           notconnec 1260      full    10G     10Gbase-SR
            Eth1/2        **********            notconnec 1260      full    10G     10Gbase-SR
            Eth1/3        **********          notconnec 1260      full    10G     10Gbase-SR
            Eth1/4        **********           sfpAbsent 1260      full    10G     --
            Eth1/5        **********            sfpAbsent 1260      full    10G     --
            --------------------- Output Truncated---------------------------------------
        hostname:
            status

            --------------------------------------------------------------------------------
            Port          Name               Status    Vlan      Duplex  Speed   Type
            --------------------------------------------------------------------------------
            Eth1/1       **********           notconnec 1260      full    10G     10Gbase-SR
            Eth1/2        **********            notconnec 1260      full    10G     10Gbase-SR
            Eth1/3        **********          notconnec 1260      full    10G     10Gbase-SR
            Eth1/4        **********           sfpAbsent 1260      full    10G     --
            Eth1/5        **********            sfpAbsent 1260      full    10G     --
            --------------------- Output Truncated---------------------------------------
        interface_list:
            - notconnec
            - Ethernet1/3
            - Ethernet1/4
            - Ethernet1/5
            - Ethernet1/6
            - Ethernet1/7
            - Ethernet1/8
            - Ethernet1/9
            - Ethernet1/10
            - Ethernet1/11
            - Ethernet1/12
            - Ethernet1/13
            - Ethernet1/14
            - Ethernet1/15
            - Ethernet1/16
            - Ethernet1/17
            - Ethernet1/18
            - Ethernet1/19
            - Ethernet1/20
            - Ethernet1/21
            - Ethernet1/22
            - Ethernet1/23
            - Ethernet1/24
            - Ethernet1/25
            - Ethernet1/26
            - Ethernet1/27
            - Ethernet1/28
            - Ethernet1/29
            - Ethernet1/30
            - Ethernet1/31
            - Ethernet1/32
            - Port-channel1
            - Port-channel13
            - Port-channel14
            - Port-channel15
            - Port-channel16
            - Port-channel17
            - Port-channel18
            - Port-channel25
            - Port-channel26
            - Port-channel27
            - Port-channel33
            - Port-channel107
            - Port-channel118
            - show
            - Port-channel119
            - mgmt0
            - host#
            - DNS
            - Default
            - Name/address
            - Name
            - Host
        model:
            Nexus5548 Chassis
        os_version:
            7.0(6)N1(1)
        serial_number:
        uptime:
            130765435
        vendor:
            Cisco
    result:
        True
```

**Comment by VictorPavlushin** [comment] 2019-11-14 04:32
@saifk-20786 
You have firmware version 7 on your device.
Please give `show inventory | json` and `show inventory`

Also try on the site https://regex101.com/ to check your console output with regexp `^NAME:\s+\"(.*)\",.*\n^PID:.*SN:\s+(\w*)`

**Comment by VictorPavlushin** [comment] 2019-11-14 04:38
@saifk-20786 And tell me which version of python you have?

**Comment by saifk-20786** [comment] 2019-11-14 14:30
> @saifk-20786 And tell me which version of python you have?

```
python --version
Python 2.7.12
```

**Comment by saifk-20786** [comment] 2019-11-14 14:51
net.facts is working as expected. Thanks @VictorPavlushin @ktbyers @mirceaulinic

**Comment by mirceaulinic** [comment] 2019-11-15 08:20
Closing as @saifk-20786 confirmed that https://github.com/napalm-automation/napalm/pull/1084 solved the issues. Thanks @VictorPavlushin.

**Closed by mirceaulinic** 2019-11-15 08:20 UTC
Labels: bug, nxos-ssh
