### ISSUE TITLE
napalm.get_bgp_neighbors on EOS showing "-1" for accepted prefixes wrt IPV4 & IPV6 

### ISSUE THREAD

**Issue by netwninja** [napalm-automation/napalm#1062] opened 2019-10-09 06:44 UTC
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
EOS<192.168.10.1>------EBGP------<192.168.10.2>IOS 
### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
root@napalm:~# pip freeze | grep napalm
napalm==2.4.0
napalm-base==1.0.0
napalm-eos==0.6.1
napalm-ios==0.8.1

```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Arista vEOS
Hardware version:    
Serial number:       
System MAC address:  5000.002f.d8fe

Software image version: 4.21.1.1F
Architecture:           i386
Internal build version: 4.21.1.1F-10146868.42111F
Internal build ID:      ed3973a9-79db-4acc-b9ac-19b9622d23e2

Uptime:                 0 weeks, 0 days, 1 hours and 34 minutes
Total memory:           2016668 kB
Free memory:            1133680 kB

```

### Steps to Reproduce the Issue. Use the below commands on EOS.

```
ip prefix-list IOS_IN seq 10 permit 3.3.3.3/32
!
route-map IOS_IN permit 10
   match ip address prefix-list IOS_IN
!
router bgp 300
   neighbor 192.168.10.2 remote-as 200
   neighbor 192.168.10.2 route-map IOS_IN in
   neighbor 192.168.10.2 maximum-routes 12000 
EOS-A#
```
### Show OUTPUTS from EOS 

```
EOS-A#show ip bgp summary 
BGP summary information for VRF default
Router identifier 192.168.10.1, local AS number 300
Neighbor Status Codes: m - Under maintenance
  Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State  PfxRcd PfxAcc
  192.168.10.2     4  200               73        68    0    0 01:05:35 Estab  2      1
EOS-A#
```

### NAPALM PYTHON SCRIPT 

```
import json
from napalm.base import get_network_driver
optional_args = {'transport': 'https'}
driver = get_network_driver('eos')
dev = driver(hostname='eos-a', username='ansible', password='ansible123', optional_args=optional_args)
dev.open()
dev_info = dev.get_bgp_neighbors()
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))
```
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
root@napalm:~# python eos1.py 
{
    "global": {
        "peers": {
            "192.168.10.2": {
                "address_family": {
                    "ipv4": {
                        "accepted_prefixes": -1, 
                        "received_prefixes": 2, 
                        "sent_prefixes": 0
                    }, 
                    "ipv6": {
                        "accepted_prefixes": -1, 
                        "received_prefixes": 0, 
                        "sent_prefixes": 0
                    }
                }, 
                "description": "", 
                "is_enabled": true, 
                "is_up": true, 
                "local_as": 300, 
                "remote_as": 200, 
                "remote_id": "172.16.10.2", 
                "uptime": 4153
            }
        }, 
        "router_id": "192.168.10.1"
    }
}

```

**Comment by netwninja** [comment] 2019-10-10 04:39
![NAPALM](https://user-images.githubusercontent.com/45272577/66539557-3a66d300-eadd-11e9-8763-fc7d37d2be17.png)

**Comment by TheRealBecks** [comment] 2019-10-10 18:16
@mirceaulinic If I understand correctly the json output for IPv4 is exactly that what @netwninja posted in his screenshot. In the eos.py file the keys 'sent' and 'received' are referenced and the section for 'accepted' is not yet implemented:
https://github.com/napalm-automation/napalm/blob/d2133692c3a58760f535da3765689bcbfafa17f1/napalm/eos/eos.py#L535-L558
But in the screenshot I can see the keys 'prefixReceived' and 'prefixAccepted'. Are the implemented keys in eos.py wrong? Also what about 'sent', I can't see that information in the screenshot. If that's the case the new code could be like this:
https://github.com/TheRealBecks/napalm/blob/0aac6ffad340fe856bed92d891f360f8bbc3a917/napalm/eos/eos.py#L535-L562
Nevertheless 'sent' is not changed.

Am I wrong? :)

**Comment by mirceaulinic** [comment] 2020-11-30 13:35
This method needs to return the number of accepted prefixes per AF. The problem is that this information is not granularly returned from the device in this form:

`sh ip bgp neighbors vrf all` returns (excerpt), e.g.,

```
  Prefix Statistics:
                                   Sent      Rcvd
    IPv4 Unicast:                     1         1
    IPv4 with MPLS Labels:            1       354
    IPv6 Unicast:                     0         0
```

So only Sent and Received counters are there, no Accepted.

In the output shared above:

```
EOS-A#show ip bgp summary 
BGP summary information for VRF default
Router identifier 192.168.10.1, local AS number 300
Neighbor Status Codes: m - Under maintenance
  Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State  PfxRcd PfxAcc
  192.168.10.2     4  200               73        68    0    0 01:05:35 Estab  2      1
EOS-A#
```

Accepted prefixes is presented, but not per AF/SAF, which is what `get_bgp_neighbors` requires to return the data accurately. Thoughts?

**Comment by netwninja** [comment] 2020-12-13 20:56
> This method needs to return the number of accepted prefixes per AF. The problem is that this information is not granularly returned from the device in this form:
> 
> `sh ip bgp neighbors vrf all` returns (excerpt), e.g.,
> 
> ```
>   Prefix Statistics:
>                                    Sent      Rcvd
>     IPv4 Unicast:                     1         1
>     IPv4 with MPLS Labels:            1       354
>     IPv6 Unicast:                     0         0
> ```
> 
> So only Sent and Received counters are there, no Accepted.
> 
> In the output shared above:
> 
> ```
> EOS-A#show ip bgp summary 
> BGP summary information for VRF default
> Router identifier 192.168.10.1, local AS number 300
> Neighbor Status Codes: m - Under maintenance
>   Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State  PfxRcd PfxAcc
>   192.168.10.2     4  200               73        68    0    0 01:05:35 Estab  2      1
> EOS-A#
> ```
> 
> Accepted prefixes is presented, but not per AF/SAF, which is what `get_bgp_neighbors` requires to return the data accurately. Thoughts?

Sorry, didn't see this message. Yes, your findings or statement is correct. Is there something specific you want me to try in the LAB ? 

Gaurav Sood

**Comment by mirceaulinic** [comment] 2022-02-13 18:28
Closing as there's not much we can do here until this information is provided by EOS.

**Closed by mirceaulinic** 2022-02-13 18:28 UTC
Labels: bug, eos
