### ISSUE TITLE
Get network driver error

### ISSUE THREAD

**Issue by bDrwx** [napalm-automation/napalm#616] opened 2018-01-09 11:10 UTC
Hi. When i try load network module for 'ios' device i get the error. But 'eos' work fine.

➜  ~ python          
Python 2.7.6 (default, Nov 23 2017, 15:50:55) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> get_network_driver('eos')
<class 'napalm.eos.eos.EOSDriver'>
>>> get_network_driver('ios')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/__init__.py", line 95, in get_network_driver
    install_name=module_install_name
napalm.base.exceptions.ModuleImportError: Cannot import "napalm.ios". Is the library installed?

**Comment by dbarrosop** [comment] 2018-01-09 11:25
Couldn't reproduce. Can you do this and paste the output?

```
$ python -c "from napalm.ios import IOSDriver"
```

If there is no output it means it worked just fine.

**Comment by bDrwx** [comment] 2018-01-09 11:32
python -c "from napalm.ios import IOSDriver"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/__init__.py", line 16, in <module>
    from napalm.ios.ios import IOSDriver
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 28, in <module>
    from netmiko import ConnectHandler, FileTransfer, InLineTransfer
  File "/usr/local/lib/python2.7/dist-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 13, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 34, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 12, in <module>
    from cryptography.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/exceptions.py", line 7, in <module>
    from enum import Enum
ImportError: No module named enum

**Comment by bDrwx** [comment] 2018-01-09 12:19
Answer is here: 
https://stackoverflow.com/questions/26828206/importerror-no-module-named-enum

pip install --upgrade pip enum34

**Comment by dbarrosop** [comment] 2018-01-09 12:31
Nice! did that solve your problem? Can we close this issue?

**Comment by bDrwx** [comment] 2018-01-09 13:28
Yes. This solved the problem. Can close issue.

**Closed** 2018-01-09 13:54 UTC
Labels: cannot reproduce, question
