### ISSUE TITLE
Validation failure for non_string items in the list

### ISSUE THREAD

**Issue by demystifier** [napalm-automation/napalm#655] opened 2018-02-16 22:30 UTC
re.search() gets upset [here](https://github.com/napalm-automation/napalm/blob/2d08e66e9be779b59ec86eb347a1fed0c14ad00f/napalm/base/validate.py#L142) if there are non_string objects in the list. 

sample data to reproduce:  [collected by get_route_to module]

src=[{'outgoing_interface': 'Port-Channel2', 'routing_table': 'default', 'protocol_attributes': {}, 'age': 0, 'protocol': 'connected', 'selected_next_hop': True, 'next_hop': '', 'last_active': True, 'current_active': True, 'preference': 0, 'inactive_reason': ''}]

dst=[{'outgoing_interface': 'Port-Channel1', 'last_active': True, 'routing_table': 'default', 'protocol_attributes': {}, 'age': 0, 'inactive_reason': '' , 'protocol': 'connected', 'current_active': True, 'preference': 0, 'selected_next_hop': True, 'next_hop': ''}]

**Comment by itdependsnetworks** [comment] 2018-02-16 22:38
Can you provide the error?

**Comment by demystifier** [comment] 2018-02-16 22:54
Here is the error:

> The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_p1qr4fdl/ansible_module_napalm_validate.py", line 261, in <module>
>     main()
>   File "/tmp/ansible_p1qr4fdl/ansible_module_napalm_validate.py", line 240, in main
>     compliance_report = get_compliance_report(module, device)
>   File "/tmp/ansible_p1qr4fdl/ansible_module_napalm_validate.py", line 138, in get_compliance_report
>     return device.compliance_report(module.params['validation_file'])
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/base.py", line 1585, in compliance_report
>     validation_source=validation_source)
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 194, in compliance_report
>     report[key] = compare(expected_results, actual_results)
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 126, in compare
>     return _compare_getter_dict(src, dst, mode)
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 82, in _compare_getter_dict
>     intermediate_result = compare(src_element, dst_element)
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 143, in compare
>     for x, y in pairs if x != y]
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 143, in <listcomp>
>     for x, y in pairs if x != y]
>   File "/usr/local/lib/python3.5/dist-packages/napalm/base/validate.py", line 142, in <listcomp>
>     for k in x if not re.search(x[k], y[k])]
>   File "/usr/lib/python3.5/re.py", line 173, in search
>     return _compile(pattern, flags).search(string)
>   File "/usr/lib/python3.5/re.py", line 292, in _compile
>     raise TypeError("first argument must be string or compiled pattern")
> TypeError: first argument must be string or compiled pattern
> 

The error is triggered when it tries to compare keys with non_string values. in above example it ends up trying to run  re.search(True,True) or re.search({},{})

**Comment by itdependsnetworks** [comment] 2018-02-17 00:59
Seems odd that this was not caught earlier, as anything but a string would have been an issue. We can check for type before, but personally wouldn't want add more logic to the list comprehension than is already there. Are the core maintainers ok with breaking this up into a for loop and some conditionals?

**Comment by dbarrosop** [comment] 2018-02-17 11:54
I suspect that's a problem on your validation rules as you shouldn't be hitting that code. Make sure you haven't forgotten to specify you are comparing lists:

https://github.com/napalm-automation/napalm/blob/develop/test/base/validate/mocked_data/strict_pass/validate.yml#L33

I know it feels a bit counter-intuitive to have to add an extra layer to specify it's a list but it's basically so you can also specify options like the "strict mode".

I am closing this issue as I couldn't reproduce myself and I suspect the issue is the one I described yourself but feel free to comment/reopen if needed.

**Closed by dbarrosop** 2018-02-17 11:54 UTC
